base: 'https://powermail-site.ddev.site/'
dependencies:
  - bootstrap-package/full
  - in2code/powermail-main
  - in2code/powermail-marketing
languages:
  -
    title: German
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ''
    flag: de
    websiteTitle: 'EXT:powermail Entwicklungspaket'
  -
    title: English
    enabled: true
    languageId: 1
    base: /en
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    fallbackType: fallback
    fallbacks: '0'
    direction: ''
    flag: us
rootPageId: 1
websiteTitle: 'EXT:powermail development package'
